### ISSUE TITLE
Add configuration man page

### ISSUE THREAD

**Issue by GabrielGanne** [mmlabs-mindmaze/mmpack#1]
This follow discussion with @lucabaldesi in https://review.gerrithub.io/c/mmlabs-mindmaze/mmpack/+/482699

There currently is no man page for configuration (to link to from the mmpack man page)
let's add one

**Comment by lucabaldesi** [comment]
This should fix it:
https://review.gerrithub.io/c/mmlabs-mindmaze/mmpack/+/484173/1
