### ISSUE TITLE
Add some way to generate package using git describe

### ISSUE THREAD

**Issue by GabrielGanne** [mmlabs-mindmaze/mmpack#2]
When creating packages from git, add a new way to automatically get a version string using `git describe`.
This is to generate more obvious package names with the CI process to fill the unstable repository.

**Comment by nbourdau** [comment]
PR open on gerrithub: https://review.gerrithub.io/c/mmlabs-mindmaze/mmpack/+/484087

**Comment by GabrielGanne** [comment]
why not use mmpack-guess instead ?
then it's just a matter of doing a release, and there you need to version bump anyway

**Comment by nbourdau** [comment]
I don't see in which way using mmpack-guess would help for this feature... According to me it is the right tool to generate an initial packaging structure, but you are supposed to inspect the result before using it. Do you intend to execute mmpack-guess in the mmpack-builder CI server on each commit that get merged?

**Comment by GabrielGanne** [comment]
I intend to deal with releases separately.

The same way I do not auto-patch the `configure.ac` using autoconf,  nor the `meson.build` files using meson, I'd rather not auto-patch the `mmpack/specs` using mmpack-build.

I also don't expect the CI to understand about git tags (even though it might)

**Comment by lucabaldesi** [comment]
My two cents:
 - version is supposed to be passed by specs file
 - in case version is not present in specs file, it is guessed through mmpack-guess
 - mmpack-build pkg-create is agnostic wrt the source format (and I think it should stay like this)
Hence, it makes sense to extend mmpack-guess to consider 'git describe' for deriving the version

**Comment by GabrielGanne** [comment]
After discussion, this is a concern more about CI (any project, not especially mmpack) than mmpack itself.
The issue is that we do not wish to version-bump every commit, but still want to be able to differentiate the various mmpack packages generated, and uploaded to `unstable` in between two releases.
Let's propose a new tool to be used by the CI to deal with that instead.

The resulting script may be located within the devtools folder, so I'm keeping this open to receive new proposals.
